#!/bin/bash
if [[ "$UID" != "0" ]]
then
    pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
else
    pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
fi

[[ -z "${pid}" ]] && exit 0
echo "${pid}" | xargs kill -"${1:-9}"
