#!/bin/zsh

completion_dir="${0:a:h}/../completions"
completion_files=("_poetry" "_bitwarden" "_terraform_docs" "_yarn" "_gh")

[[ ! -d "${completion_dir}" ]] && mkdir -p "${completion_dir}"

if [[ "$OS_DISTRO" =~ .*UBUNTU ]]; then
	default_completion_dir="/home/linuxbrew/.linuxbrew/share/zsh/site-functions"
fi

function _activate_completion() {
	echo "" >>"$1"
	head -1 "$1" | cut -c 2- >>"$1"
}

for completion_file in "${completion_files[@]}"; do
	completion_file_path="${completion_dir}/${completion_file}"
	case "${completion_file}" in
	_poetry)
		if command -v poetry &>/dev/null; then
			poetry completions zsh >"${completion_file_path}"
		fi
		;;
	_bitwarden)
		if command -v bw &>/dev/null; then
			bw completion --shell zsh >"${completion_file_path}"
			_activate_completion "${completion_file_path}"
		fi
		;;
	_terraform_docs)
		if command -v terraform-docs &>/dev/null; then
			terraform-docs completion zsh >"${completion_file_path}"
			_activate_completion "${completion_file_path}"
		fi
		;;
	_yarn)
		if command -v yarn &>/dev/null; then
			curl https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_yarn >"${completion_file_path}"
			_activate_completion "${completion_file_path}"
		fi
		;;
  _gh)
    if command -v gh &>/dev/null; then
      gh completion -s zsh >"${completion_file_path}"
      _activate_completion "${completion_file_path}"
    fi
    ;;
	esac
done

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
zinit creinstall "${completion_dir}"

[[ -d "${default_completion_dir}" ]] && zinit creinstall "${default_completion_dir}"
